version: '3.8'
services:
  zcsw-workspace-ubuntu:
    build:
      context: .
      args:
        WITH_GCC: ${WITH_GCC}
        WITH_LLVM: ${WITH_LLVM}
        WITH_RUST: ${WITH_RUST}
        WITH_GO: ${WITH_GO}
        DISABLE_SNAP: ${DISABLE_SNAP}
        WITH_ZSH: ${WITH_ZSH}
        CONFIG_GITHUB: ${CONFIG_GITHUB}
        WITH_ASTRONVIM: ${WITH_ASTRONVIM}
        WITH_VSCODE: ${WITH_VSCODE}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER_NAME: ${USER_NAME}
        GROUP_NAME: ${GROUP_NAME}
        HOME_DIR: ${HOME_DIR}
        MOUNT_PATH: ${MOUNT_PATH}
        GH_TOKEN: ${GH_TOKEN}
        CODE_COMMITID: ${CODE_COMMITID}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        PROXY_ENABLED: ${PROXY_ENABLED}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "2222:22"
    network_mode: bridge
    volumes:
      - ${MOUNT_PATH}:${MOUNT_PATH}
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    user: "${USER_ID}:${GROUP_ID}"
