version: '3.8'
services:
  zcsw-workspace-ubuntu:
    build:
      context: .
      args:
        WITH_GCC: ${WITH_GCC}
        WITH_LLVM: ${WITH_LLVM}
        WITH_RUST: ${WITH_RUST}
        WITH_GO: ${WITH_GO}
        DISABLE_SNAP: ${DISABLE_SNAP}
    image: zcsw-workspace-ubuntu
    container_name: zcsw-workspace-ubuntu-container
    ports:
      - "2222:22"  # 映射宿主机的 2222 端口到容器的 22 端口
    network_mode: bridge
    volumes:
      - ${MOUNT_PATH}:${MOUNT_PATH}
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - USER_NAME=${USER_NAME}
      - GROUP_NAME=${GROUP_NAME}
      - HOME_DIR=${HOME_DIR}
      - MOUNT_PATH=${MOUNT_PATH}
      - WITH_ZSH=${WITH_ZSH}
      - CONFIG_GITHUB=${CONFIG_GITHUB}
      - WITH_ASTRONVIM=${WITH_ASTRONVIM}
      - WITH_VSCODE=${WITH_VSCODE}
    user: "${USER_ID}:${GROUP_ID}"
